# Generated by Django 2.2.8 on 2019-12-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClippingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clipping_creator', models.CharField(default='Sala de Situação da FS/UnB', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='published date')),
                ('human_pub_date', models.CharField(default='0', max_length=500)),
                ('author', models.CharField(default='0', max_length=500)),
                ('url_to_image', models.CharField(default='0', max_length=500)),
                ('image', models.ImageField(blank=True, max_length=1000, upload_to='gerador/jasper/images')),
                ('source_db_id', models.CharField(default='0', max_length=500)),
                ('header', models.CharField(default='', max_length=500)),
                ('clipping_creator', models.CharField(default='Sala de Situação da FS/UnB', max_length=2000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerador.ClippingProject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
