# Generated by Django 2.2.6 on 2019-11-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=100000)),
                ('url', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='published date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerador.ClippingProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
