# Generated by Django 2.2.8 on 2019-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='clipping_creator',
            field=models.CharField(default='Elaborado por <br> Sala de Situação da FS/UnB', max_length=2000),
        ),
    ]
