# Generated by Django 2.2.6 on 2019-11-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0002_auto_20191114_0928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
