# Generated by Django 2.2.6 on 2019-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0003_auto_20191114_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='clippingproject',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
