# Generated by Django 2.2.6 on 2019-11-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0004_clippingproject_is_archived'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
    ]
