# Generated by Django 2.2.6 on 2019-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0005_auto_20191119_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='source_db_id',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AddField(
            model_name='news',
            name='url_to_image',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
