# Generated by Django 2.2.7 on 2019-11-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0006_auto_20191119_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='index',
        ),
    ]
