# Generated by Django 2.2.7 on 2019-11-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0008_auto_20191121_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='header',
            field=models.CharField(default='', max_length=50),
        ),
    ]
