# Generated by Django 2.2.7 on 2019-11-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0009_news_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_db_id',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_to_image',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
