# Generated by Django 2.2.7 on 2019-12-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0010_auto_20191126_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
