# Generated by Django 2.2.7 on 2019-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0011_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, upload_to='gerador/static/gerador/jasper/images'),
        ),
    ]
