# Generated by Django 2.2.8 on 2019-12-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0012_auto_20191201_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, upload_to='gerador/jasper/images'),
        ),
    ]
