# Generated by Django 2.2.8 on 2019-12-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0013_auto_20191202_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='human_pub_date',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
