# Generated by Django 2.2.8 on 2019-12-03 22:10

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gerador', '0014_news_human_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, max_length=1000, quality=0, size=[507, 90], upload_to='gerador/jasper/images'),
        ),
    ]
